---
- name: INVENTORIES - Count inventory hosts
  hosts: localhost
  gather_facts: false

  tasks:
    - name: INVENTORIES - Build list with host count for each inventory
      ansible.builtin.set_fact:
        controller_objects_inventory_host_count: "{{ controller_objects_inventory_host_count | default([]) +
                                                     [{'name': item.name,
                                                       'host_count': lookup('ansible.controller.controller_api',
                                                                            'inventories/' +
                                                                              item.id | string +
                                                                              '/hosts/',
                                                                            return_objects=false,
                                                                            return_all=true).results | length} |
                                                     regex_replace('\n', '')] }}"
      loop: "{{ lookup('ansible.controller.controller_api', 'inventories/', return_objects=false, return_all=true).results }}"
      loop_control:
        label: " | inventory: {{ item.name }}"

    - name: INVENTORIES - Show host count
      ansible.builtin.debug:
        var: controller_objects_inventory_host_count
      when: >
            controller_objects_inventory_host_count is defined and
            controller_objects_inventory_host_count and
            not show_vars_at_the_end | default(false)
